# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0003_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='isim')),
                ('content', models.TextField(verbose_name='yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postApp.post')),
            ],
        ),
    ]
