# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yorum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postApp.post'),
        ),
    ]
